combine_control_expr = false
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
enum_discrim_align_threshold = 30
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
hex_literal_case = "Lower"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 80
imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
struct_field_align_threshold = 30
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
