[package]
name = "raven"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
internment = "0.7.0"
num = { version = "0.4.0", features = ["num-bigint"] }
